name: Scrape Wikipedia

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests regex
      
      - name: Run Scraper
        run: python scraper.py
      
      - name: Commit Changes
        run: |
          git config --global user.email "bar@securityjoes.com"
          git config --global user.name "bmoyall"
          git add .
          git diff --exit-code || git commit -am "ci lint and test"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
