name: Scrape Wikipedia

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install Dependencies
        run: |
          pip install beautifulsoup4 requests regex
          
      - name: Run Scraper
        run: python scraper.py
          
      - name: Commit Changes
        run: |
          git config --global user.email "bar@securityjoes.com"
          git config --global user.name "bmoyall"
          git add .
          git diff --exit-code || git commit -m "Auto Update"
          git push
